In [112]:
import cv2
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
import matplotlib.image as im

In [113]:
def photo():
    fname=input("Enter file name: ")
    try:
        opn=os.listdir(fname)
    except:
        print("File not Found")
    else:
        img_dir=glob.glob("photos/*.jpg")  
        c=0
        for i in img_dir:
            c+=1
            print(i)
        print("Number of files is = ",c)
    


In [114]:
def imagresize():
    #numpy=np.array([22,200,200,3])
    for ims in img_dir:
        i=Image.open(ims)
        print(i)
        arr1=i.resize((200,200))
        print(arr1)
        numpy=np.array(arr1)
        print(numpy)
        print("*"*25)

In [115]:
def main():
    photo()
    imagresize()
    #print("Print final array: ",s)

In [116]:
if __name__ == "__main__":
    main()


Enter file name: 
File not Found
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=321x157 at 0x20730267390>
<PIL.Image.Image image mode=RGB size=200x200 at 0x20730267518>
[[[  0   0   2]
  [  3   4   6]
  [  7   8  10]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   2]
  [  3   4   6]
  [  7   8  10]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   2]
  [  3   4   6]
  [  7   8  10]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 22  27  33]
  [ 19  24  30]
  [ 14  19  25]
  ...
  [249 251 246]
  [249 251 246]
  [248 249 244]]

 [[ 22  27  33]
  [ 19  24  30]
  [ 14  19  25]
  ...
  [249 251 246]
  [249 251 246]
  [248 249 244]]

 [[  5   8  15]
  [  4   7  14]
  [  1   4  11]
  ...
  [248 250 245]
  [248 250 245]
  [247 248 242]]]
*************************
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1920x1080 at 0x20730267860>
<PIL.Image.Image image mode=RGB size=200x200 at 0x20730267390>
[[[0 0 0]
  [0 0 0]
 

In [117]:
print(__name__)

__main__


In [118]:
# %%
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
rootDir = 'photos'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
    

# %%
main_list = []
im = Image.open(dirName+"\\"+fileList[0])
print("----------X------------X-----------------------X\n\n")
im.show()
original_array = np.array(im)
print(original_array.shape)
print(original_array.size)
print(original_array)
print("\n\n----------X------------X-----------------------X\n\n")
new_image = im.resize((200, 200))
resized_array = np.array(new_image)
print(resized_array.size)
print(resized_array.shape)
print(resized_array)
main_list.append(resized_array)

# %%
main_list

# %%
pic = 2
for i in range(1,len(fileList)):
    print("PIC NO : ",pic)
    im = Image.open(dirName+"\\"+fileList[i])           
    print("----------X------------X-----------------------X\n\n")
    im.show()
    original_array = np.array(im)
    print(original_array.shape)
    print(original_array.size)
    print(original_array)
    print("\n\n----------X------------X-----------------------X\n\n")
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    print(resized_array.size)
    print(resized_array.shape)
    print(resized_array)
    print("APPENDING TIME")
    main_list.append(resized_array)
    pic = pic+1

# %%
len(main_list)

# %%
main_list

# %%
def main():
    
    main_arr= np.array(main_list)
    print("FINAL NUMPY ARRAY :\n\n ",main_arr)
    return main_arr

# %%
# main_arr = main()
# main_arr

# %%
main_arr.shape

# %%
main_arr.ndim

# %%
main_arr.size

# %%


Found directory: photos
	1d.jpg
	34906(1).png
	34906.jpg
	color-wing (1).jpg
	color-wing.jpg
	download (1).jpg
	download (2).jpg
	download (3).jpg
	download (4).jpg
	download (5).jpg
	download (6).jpg
	download (7).jpg
	download (8).jpg
	download (9).jpg
	download2.jpg
	images (1).jpg
	images (2).jpg
	images (3).jpg
	images (4).jpg
	images (5).jpg
	images (6).jpg
	images (7).jpg
	images.jpg
----------X------------X-----------------------X


(157, 321, 3)
151191
[[[  0   0   2]
  [  0   0   2]
  [  3   4   6]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   2]
  [  0   0   2]
  [  3   4   6]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   2]
  [  0   0   2]
  [  3   4   6]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 29  34  40]
  [ 27  32  38]
  [ 24  29  35]
  ...
  [250 252 247]
  [250 252 247]
  [249 250 245]]

 [[ 22  27  33]
  [ 21  26  32]
  [ 19  24  30]
  ...
  [249 251 246]
  [249 251 246]
  [248 249 244]]

 [[  5  

(259, 194, 3)
150738
[[[29 34 30]
  [29 34 30]
  [30 35 31]
  ...
  [40 49 44]
  [42 47 43]
  [42 47 43]]

 [[25 30 26]
  [26 31 27]
  [26 31 27]
  ...
  [34 43 38]
  [35 40 36]
  [35 40 36]]

 [[22 27 23]
  [23 28 24]
  [23 28 24]
  ...
  [27 36 31]
  [31 36 32]
  [31 36 32]]

 ...

 [[44 46 45]
  [37 39 38]
  [40 42 41]
  ...
  [28 28 26]
  [28 28 28]
  [28 28 28]]

 [[44 46 45]
  [37 39 38]
  [40 42 41]
  ...
  [28 28 26]
  [28 28 28]
  [28 28 28]]

 [[44 46 45]
  [37 39 38]
  [39 41 40]
  ...
  [28 28 26]
  [28 28 28]
  [28 28 28]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[29 34 30]
  [29 34 30]
  [30 35 31]
  ...
  [40 49 44]
  [42 47 43]
  [42 47 43]]

 [[25 30 26]
  [26 31 27]
  [26 31 27]
  ...
  [34 43 38]
  [35 40 36]
  [35 40 36]]

 [[23 28 24]
  [24 29 25]
  [24 29 25]
  ...
  [25 34 29]
  [33 38 34]
  [33 38 34]]

 ...

 [[35 37 36]
  [32 34 33]
  [36 38 37]
  ...
  [23 25 22]
  [28 30 27]
  [28 30 27]]

 [[44 46 45]
  [37 39 38]
  [40 4

(168, 300, 3)
151200
[[[66 57 48]
  [72 63 54]
  [81 71 61]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[43 36 28]
  [57 48 39]
  [73 64 55]
  ...
  [14 14 14]
  [12 12 12]
  [ 9  9  9]]

 [[27 22 16]
  [39 32 24]
  [52 45 37]
  ...
  [34 34 34]
  [26 26 26]
  [17 17 17]]

 ...

 [[18 17 13]
  [17 16 12]
  [17 16 12]
  ...
  [50 36 25]
  [47 33 22]
  [44 30 19]]

 [[21 20 16]
  [20 19 15]
  [18 17 13]
  ...
  [82 66 51]
  [78 62 47]
  [76 60 45]]

 [[24 23 19]
  [22 21 17]
  [19 18 14]
  ...
  [96 77 62]
  [93 74 59]
  [90 71 56]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[66 57 48]
  [81 71 61]
  [90 78 66]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[43 36 28]
  [73 64 55]
  [83 73 63]
  ...
  [15 15 15]
  [14 14 14]
  [ 9  9  9]]

 [[27 22 16]
  [52 45 37]
  [66 57 48]
  ...
  [40 40 40]
  [34 34 34]
  [17 17 17]]

 ...

 [[18 17 13]
  [17 16 12]
  [15 14 10]
  ...
  [52 38 27]
  [50 36 25]
  [44 30 19]]

 [[21 20 16]
  [18 17 13]
  [15 1

(177, 284, 3)
150804
[[[129  78  47]
  [136  85  54]
  [137  86  55]
  ...
  [120  63  33]
  [120  63  33]
  [123  64  34]]

 [[133  82  51]
  [138  87  56]
  [137  86  55]
  ...
  [111  54  24]
  [112  55  25]
  [114  55  25]]

 [[146  93  62]
  [152  99  68]
  [150  97  66]
  ...
  [107  50  20]
  [108  51  21]
  [108  51  21]]

 ...

 [[ 93  50  18]
  [ 94  49  18]
  [100  55  24]
  ...
  [114  82  61]
  [ 90  58  37]
  [ 75  44  23]]

 [[ 86  43  11]
  [108  65  33]
  [ 88  43  12]
  ...
  [116  83  64]
  [ 88  55  36]
  [ 73  42  22]]

 [[ 89  54  35]
  [ 90  53  35]
  [ 89  52  33]
  ...
  [ 95  61  36]
  [ 91  59  36]
  [ 63  35  14]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[129  78  47]
  [137  86  55]
  [132  81  50]
  ...
  [119  62  33]
  [120  63  33]
  [123  64  34]]

 [[133  82  51]
  [137  86  55]
  [129  78  47]
  ...
  [111  54  25]
  [111  54  24]
  [114  55  25]]

 [[146  93  62]
  [150  97  66]
  [142  89  58]
  ...
  [106  51  2

NameError: name 'main_arr' is not defined

In [ ]:
main_list=[]
def photo():
    fname=input("Enter file name: ")
    try:
        opn=os.listdir(fname)
    except:
        print("File not Found")
    else:
        img_dir=glob.glob("photos/*.jpg")  
        c=0
        for i in img_dir:
            c+=1
            print(i)
        print("Number of files is = ",c)

In [ ]:
def arraystore():
    for ims in img_dir:
        i=Image.open(ims)
        i.show()
        arr1=np.array(i)
        numpy=arr1
        #print(numpy.shape+"\n"+numpy.ndim+"\n"+numpy.size)
        print("*"*25)
        print(numpy)
    
def arayresize():
     for ims in img_dir:
        i=Image.open(ims)
        arr1=i.resize((200,200))
        numpy=np.array(arr1)
        main_list.append(numpy)
        print(numpy.shape+"\n"+numpy.ndim+"\n"+numpy.size)
        print("*"*25)
        print(numpy)
    
    


In [ ]:
def main():
    photo()
    arraystore()
    arayresize()
    main_arra=np.array(main_list)
    print("Final Numpy Array :\n\n",main_arra)
    return main_arra

In [ ]:
main_arra=main()
main_arra
print(main_arra.shape)
main_arra.ndim
main_arra.size

In [ ]:
main_list=[]
def photo():
    fname=input("Enter file name: ")
    try:
        opn=os.listdir(fname)
    except:
        print("File not Found")
    else:
        img_dir=glob.glob("photos/*.jpg")  
        c=0
        for i in img_dir:
            c+=1
            print(i)
        print("Number of files is = ",c)
def arayresize():
     for ims in img_dir:
        i=Image.open(ims)
        arr1=i.resize((200,200))
        numpy=np.array(arr1)
        print(numpy.shape)
        print(numpy.size)
        main_list.append(numpy)
        np.savez("x_array",main_list)
        #print(numpy.shape+"\n"+numpy.ndim+"\n"+numpy.size)
        print("*"*25)
        #print(numpy)
        x_npz = np.load("x_array.npz")
        x = x_npz['arr_0']
        print(x)

In [ ]:
photo()
arayresize()